name: Bicep-CD

on:
  push:
    branches: [ main ]
    paths:
      - '**.bicep'
  workflow_dispatch:

jobs:
  DEV-BICEP-CD:
    runs-on: ubuntu-latest
    env:
      BICEP_PATH: ./bicep/custom-polices-with-notifications
      LOCATION: westeurope
      DEV_PARAMS: params-dev.json
    steps:
      - uses: actions/checkout@v2
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}
      - name: Deploy Bicep Template
        id: bicepCD
        continue-on-error: true
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az deployment sub create \
              -n dev-bicep-cd \
              -f ${{ env.BICEP_PATH }}/main.bicep \
              -l ${{ env.LOCATION }} \
              -p ${{ env.BICEP_PATH }}/${{ env.DEV_PARAMS }} \
              -o none
      - name: Retry on Failure
        if: ${{ steps.bicepCD.outcome == 'failure' }}
        uses: juliangruber/sleep-action@v1
        with:
          time: 30s
      - name: Bicep CD Retry
        if: ${{ steps.bicepCD.outcome == 'failure' }}
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az deployment sub create \
              -n dev-bicep-cd \
              -f ${{ env.BICEP_PATH }}/main.bicep \
              -l ${{ env.LOCATION }} \
              -p ${{ env.BICEP_PATH }}/${{ env.DEV_PARAMS }} \
              -o none

  NONPROD-BICEP-CD:
    needs: DEV-BICEP-CD
    runs-on: ubuntu-latest
    env:
      BICEP_PATH: ./bicep/custom-polices-with-notifications
      LOCATION: westeurope
      NONPROD_PARAMS: params-nonprod.json
    steps:
      - uses: actions/checkout@v2
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_NONPROD }}
      - name: Deploy Bicep Template
        id: bicepCD
        continue-on-error: true
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az deployment sub create \
              -n nonprod-bicep-cd \
              -f ${{ env.BICEP_PATH }}/main.bicep \
              -l ${{ env.LOCATION }} \
              -p ${{ env.BICEP_PATH }}/${{ env.NONPROD_PARAMS }} \
              -o none
      - name: Retry on Failure
        if: ${{ steps.bicepCD.outcome == 'failure' }}
        uses: juliangruber/sleep-action@v1
        with:
          time: 30s
      - name: Bicep CD Retry
        if: ${{ steps.bicepCD.outcome == 'failure' }}
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az deployment sub create \
              -n nonprod-bicep-cd \
              -f ${{ env.BICEP_PATH }}/main.bicep \
              -l ${{ env.LOCATION }} \
              -p ${{ env.BICEP_PATH }}/${{ env.NONPROD_PARAMS }} \
              -o none

  PROD-BICEP-CD:
    needs: NONPROD-BICEP-CD
    runs-on: ubuntu-latest
    env:
      BICEP_PATH: ./bicep/custom-polices-with-notifications
      LOCATION: westeurope
      PROD_PARAMS: params-prod.json
    steps:
      - uses: actions/checkout@v2
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_PROD }}
      - name: Deploy Bicep Template
        id: bicepCD
        continue-on-error: true
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az deployment sub create \
              -n prod-bicep-cd \
              -f ${{ env.BICEP_PATH }}/main.bicep \
              -l ${{ env.LOCATION }} \
              -p ${{ env.BICEP_PATH }}/${{ env.PROD_PARAMS }} \
              -o none
      - name: Retry on Failure
        if: ${{ steps.bicepCD.outcome == 'failure' }}
        uses: juliangruber/sleep-action@v1
        with:
          time: 30s
      - name: Bicep CD Retry
        if: ${{ steps.bicepCD.outcome == 'failure' }}
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az deployment sub create \
              -n prod-bicep-cd \
              -f ${{ env.BICEP_PATH }}/main.bicep \
              -l ${{ env.LOCATION }} \
              -p ${{ env.BICEP_PATH }}/${{ env.PROD_PARAMS }} \
              -o none
